// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API.Models;

namespace Web_API.Migrations
{
    [DbContext(typeof(AgileDBContext))]
    [Migration("20200709060647_DB_v2")]
    partial class DB_v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_API.Models.Bar", b =>
                {
                    b.Property<int>("BarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("BarId");

                    b.ToTable("Bar");

                    b.HasData(
                        new
                        {
                            BarId = 1,
                            Name = "To-do"
                        },
                        new
                        {
                            BarId = 2,
                            Name = "Ongoing"
                        },
                        new
                        {
                            BarId = 3,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Web_API.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CardId");

                    b.HasIndex("Column");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            Column = 1,
                            Name = "Test 1"
                        },
                        new
                        {
                            CardId = 2,
                            Column = 2,
                            Name = "Test 2"
                        },
                        new
                        {
                            CardId = 3,
                            Column = 3,
                            Name = "Test 3"
                        });
                });

            modelBuilder.Entity("Web_API.Models.Card", b =>
                {
                    b.HasOne("Web_API.Models.Bar", "Bar")
                        .WithMany("Cards")
                        .HasForeignKey("Column")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
